services:
  postgres:
    container_name: mini_marketplace
    image: postgis/postgis:17-3.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mini_marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: mini_marketplace_redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    restart: always
