services:
  postgres:
    container_name: mini_marketplace
    image: postgis/postgis:17-3.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mini_marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: mini_marketplace_redis_dev
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: mini_marketplace_es_dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=mini_marketplace_cluster
      - node.name=es_node_1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

volumes:
  db_data:
  redis_data:
  es_data:
